name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGION: ${{ secrets.GCP_REGION }}
      COMMIT: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Authenticate Docker to Google Cloud
        run: |
          echo "Authenticating Docker to gcr.io, $REGION-docker.pkg.dev..."
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
          echo "Docker authentication complete."

      - name: Build Docker image
        run: |
          IMAGE_TAG="$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/staging-app-repo/app:$COMMIT"
          echo "Building Docker image: $IMAGE_TAG"
          docker build -t $IMAGE_TAG -f app/Dockerfile app/

      - name: Push Docker image to Google Container Registry
        run: |
          IMAGE_TAG="$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/staging-app-repo/app:$COMMIT"
          echo "Pushing Docker image: $IMAGE_TAG"
          docker push $IMAGE_TAG

      - name: Deploy to Google Cloud Run
        run: |
          IMAGE_TAG="$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/staging-app-repo/app:$COMMIT"
          echo "Deploying to Cloud Run with image: $IMAGE_TAG"
          gcloud run services update staging-app --image $IMAGE_TAG --platform managed --region $REGION